export const dogBreeds = [
  "Vira-lata",
  "Affenpinscher",
  "African",
  "Airedale",
  "Akita",
  "Appenzeller",
  "Australian",
  "Basenji",
  "Beagle",
  "Bluetick",
  "Borzoi",
  "Bouvier",
  "Boxer",
  "Brabancon",
  "Briard",
  "Buhund",
  "Bulldog",
  "Bullterrier",
  "Cattledog",
  "Chihuahua",
  "Chow",
  "Clumber",
  "Cockapoo",
  "Collie",
  "Coonhound",
  "Corgi",
  "Cotondetulear",
  "Dachshund",
  "Dalmatian",
  "Dane",
  "Deerhound",
  "Dhole",
  "Dingo",
  "Doberman",
  "Elkhound",
  "Entlebucher",
  "Eskimo",
  "Finnish",
  "Frise",
  "Germanshepherd",
  "Greyhound",
  "Groenendael",
  "Havanese",
  "Hound",
  "Husky",
  "Keeshond",
  "Kelpie",
  "Komondor",
  "Kuvasz",
  "Labradoodle",
  "Labrador",
  "Leonberg",
  "Lhasa",
  "Malamute",
  "Malinois",
  "Maltese",
  "Mastiff",
  "Mexicanhairless",
  "Mix",
  "Mountain",
  "Newfoundland",
  "Otterhound",
  "Ovcharka",
  "Papillon",
  "Pekinese",
  "Pembroke",
  "Pinscher",
  "Pitbull",
  "Pointer",
  "Pomeranian",
  "Poodle",
  "Pug",
  "Puggle",
  "Pyrenees",
  "Redbone",
  "Retriever",
  "Ridgeback",
  "Rottweiler",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Segugio",
  "Setter",
  "Sharpei",
  "Sheepdog",
  "Shiba",
  "Shihtzu",
  "Spaniel",
  "Spitz",
  "Springer",
  "Stbernard",
  "Terrier",
  "Tervuren",
  "Vizsla",
  "Waterdog",
  "Weimaraner",
  "Whippet",
  "Wolfhound",
];

export const catBreeds = [
  "Vira-lata",
  "Abyssinian",
  "Aegean",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Arabian Mau",
  "Australian Mist",
  "Balinese",
  "Bambino",
  "Bengal",
  "Birman",
  "Bombay",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chartreux",
  "Chausie",
  "Cheetoh",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Cyprus",
  "Devon Rex",
  "Donskoy",
  "Dragon Li",
  "Egyptian Mau",
  "European Burmese",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Javanese",
  "Khao Manee",
  "Korat",
  "Kurilian",
  "LaPerm",
  "Maine Coon",
  "Malayan",
  "Manx",
  "Munchkin",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental",
  "Persian",
  "Pixie-bob",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
  "York Chocolate",
];
